### 测试TAPD Webhook - 附件添加事件
POST http://localhost:3000/webhook/tapd
Content-Type: application/json

{
  "auto_task_id": "1164029412001000237",
  "auto_task_branch_id": "1164029412001001938",
  "workspace_id": "64029412",
  "search": null,
  "event": {
    "workspace_id": "64029412",
    "user": "李耀",
    "object_type": "story",
    "id": "1164029412001164244",
    "timestamp": 1757420574,
    "timestamp_micro": 1757420574636,
    "new": {
      "attachment_id": "1164029412001039442",
      "attachment_url": "https://file.tapd.cn/64029412/attachments/download/1164029412001039442/story",
      "content_type": "application/zip",
      "filename": "前端-【1164395】【车】【天慧】【批改类型】标签优化.xlsx",
      "id": "1164029412001164244",
      "resource_type": "attachment",
      "size": 10378,
      "sub_event": "attachment_add"
    },
    "old": {
      "id": "1164029412001164244"
    },
    "object_info": {
      "id": "1164029412001164244",
      "name": "【V20250922-临时】文档审查优化功能更新",
      "workspace_id": "64029412"
    },
    "event_key": "story::attachment",
    "from": "web",
    "event_id": "34a40806427a5354e35bb51959708568_tdjob_398-1757420540_39_2aeb6f9f0949"
  }
}
